### ISSUE TITLE
I'm try to create Smart transaction STX and have error 500

### ISSUE THREAD

**Issue by webquali** [secuconnect/secuconnect-php-sdk#11]
this my code:
$dto = new SmartTransactionsDTO();
            $stx = new SmartTransactionsApi();
            $stx->addTransaction($dto);

I have this error:

Secuconnect\Client\ApiException: [500] Error connecting to the API (https://connect-testing.secupay-ag.de/api/v2/Smart/Transactions) in file
vendor/secuconnect/secuconnect-php-sdk/lib/ApiClient.php on line 235
#0 /Users/xxx/xxx/xxx/xxx/vendor/secuconnect/secuconnect-php-sdk/lib/Api/SmartTransactionsApi.php(129): Secuconnect\Client\ApiClient-&gt;callApi('/Smart/Transact...', 'POST', Array, '{}', Array, '\\Secuconnect\\Cl...', '/Smart/Transact...')
#1/Users/xxx/xxx/xxx/xxx/vendor/secuconnect/secuconnect-php-sdk/lib/Api/SmartTransactionsApi.php(74): Secuconnect\Client\Api\SmartTransactionsApi-&gt;addTransactionWithHttpInfo(Object(Secuconnect\Client\Model\SmartTransactionsDTO))
#2 /Users/xxx/xxx/xxx/xxx/app/Http/Controllers/api/v1/PaymentController.php(77): Secuconnect\Client\Api\SmartTransactionsApi-&gt;addTransaction(Object(Secuconnect\Client\Model\SmartTransactionsDTO))

**Comment by webquali** [comment]
$dto = new SmartTransactionsDTO([]);

need prepare array with data
